In [86]:
import pandas as pd
import numpy as np

# **Q1. Pandas version**

In [87]:
pd.__version__

'2.2.2'

**Reading dataset**

In [88]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [89]:
df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

# **Q2. Records count**

In [90]:
df.shape[0]

9704

# **Q3. Fuel types**

In [91]:
df['fuel_type'].nunique()

2

# **Q4. Missing values**

In [92]:
df.isnull().any().sum()

np.int64(4)

# **Q5. Max fuel efficiency**

In [96]:
max_fuel_efficiency = df.loc[df['origin'] == 'Asia', 'fuel_efficiency_mpg'].max()
round(max_fuel_efficiency, 2)

23.76

# **Q6. Median value of horsepower**

In [97]:
# Calculating median value of horsepower
median_before = df['horsepower'].median()
median_before

149.0

In [98]:
# Calculating most frequent valur of horsepower column
most_freq = df['horsepower'].mode()[0]
most_freq

np.float64(152.0)

In [99]:
# Filling missing values with the most frequent value
df['horsepower'] = df['horsepower'].fillna(most_freq)

In [100]:
# Calculating median value again
median_after = df['horsepower'].median()
median_after

152.0

# **Q7. Sum of weights**

In [101]:
# Selecting all the cars from Asia
cars_from_asia = df[df['origin'] == 'Asia']


In [102]:
# Selecting vehicle_weight and model_year columns
cars_from_asia[['vehicle_weight', 'model_year']]

vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

In [103]:
# First 7
cars_from_asia[['vehicle_weight', 'model_year']].head(7)

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [104]:
# Numpy array
X = cars_from_asia[['vehicle_weight', 'model_year']].head(7).to_numpy()
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [105]:
# Computing matrix-matrix multiplication
XTX = np.dot(X.T, X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [106]:
# Inverting XTX
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [107]:
# Creating numpy array
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [108]:
# Multiplying matrix
w = np.dot(XTX_inv, X.T).dot(y)
w

array([0.01386421, 0.5049067 ])

In [109]:
# Sum of results
sum = w.sum()
round(sum, 2)

np.float64(0.52)